(()=>{'use strict';
const VERSION='10.1.1';
const DATA_KEY='mastarklass_os_10_data';
const LIVE_KEY='mastarklass_os_live_readonly_v1';
const SETTINGS_KEY='mastarklass_os_10_settings';
let sourceKey=null;
const NAV=[['home','🏠','Hem'],['portfolio','📊','Portfölj'],['market','🌍','Marknad'],['analysis','🧠','Analys'],['ideas','💡','Idéer'],['goals','🎯','Mål'],['more','☰','Mer']];
const DEFAULTS={portfolio:{net:0,monthly:8500,credit:0},holdings:[],accounts:[],goals:{capital:7500000,annualDividend:480000},monthlyPlan:{total:8500},marketCenter:{items:[]},ideaBank:[],aiRadar:[],reports:[],journal:[],meta:{updated:new Date().toISOString().slice(0,10)}};
let data=structuredClone(DEFAULTS),screen='home',bootError=null;
const parse=x=>{try{return JSON.parse(x)}catch{return null}};
const safeNum=x=>Number.isFinite(Number(x))?Number(x):0;
function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={...a};if(b&&typeof b==='object')for(const k of Object.keys(b))o[k]=k in a?merge(a[k],b[k]):b[k];return o}return b??a}
function looksLikePortfolio(x){return !!(x&&typeof x==='object'&&(Array.isArray(x.holdings)||Array.isArray(x.accounts)||safeNum(x.portfolio?.net)>0))}
function candidateScore(x){if(!looksLikePortfolio(x))return 0;return (x.holdings?.length||0)*20+(x.accounts?.length||0)*8+Math.min(500,safeNum(x.portfolio?.net)/1000)}
function safeGet(key){try{return localStorage.getItem(key)}catch{return null}}
function safeSet(key,value){try{localStorage.setItem(key,value);return true}catch(err){console.warn('Mästarklass storage write blocked',key,err);return false}}
function loadSettings(){return parse(safeGet(SETTINGS_KEY))||{}}
function applySettings(base){const s=loadSettings();const out=merge(DEFAULTS,base||{});if(s.goals)out.goals=merge(out.goals,s.goals);if(s.portfolio)out.portfolio=merge(out.portfolio,s.portfolio);return out}
function loadData(){const own=parse(safeGet(DATA_KEY));if(looksLikePortfolio(own)){sourceKey=DATA_KEY;return applySettings(own)}let best=null,score=0,bestKey=null;for(let i=0;i<localStorage.length;i++){const key=localStorage.key(i);if(!key||key===LIVE_KEY||key===SETTINGS_KEY||key.startsWith('mk_live_')||key.includes('cache'))continue;const raw=safeGet(key);if(!raw)continue;const value=parse(raw);const next=candidateScore(value);if(next>score){best=value;score=next;bestKey=key}}sourceKey=bestKey;return applySettings(best||{})}
function save(){const settings={goals:data.goals,portfolio:{monthly:data.portfolio?.monthly},meta:{updated:new Date().toISOString()}};if(!safeSet(SETTINGS_KEY,JSON.stringify(settings)))toast('Lagringen är full. Exportera backup innan fler ändringar.')}
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kr=n=>new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0}).format(safeNum(n))+' kr';
function holdingValue(h){const direct=safeNum(h.marketValueSEK??h.marketValue??h.value??h.currentValue);if(direct)return direct;return safeNum(h.quantity??h.qty)*safeNum(h.latestPrice??h.price)*safeNum(h.fxToSEK??h.fxRate??1)}
function total(){const holdings=data.holdings.reduce((s,h)=>s+holdingValue(h),0);return safeNum(data.portfolio?.net)||holdings||data.accounts.reduce((s,a)=>s+safeNum(a.value),0)}
function liveState(){const x=parse(safeGet(LIVE_KEY))||{};return {providers:Array.isArray(x.providers)?x.providers:[],quotes:Array.isArray(x.quotes)?x.quotes:[],fx:x.fx||{},updatedAt:x.updatedAt||null}}
function setHash(id){if(location.hash.slice(1)!==id)history.replaceState(null,'','#'+id)}
function nav(){const root=document.getElementById('nav');root.innerHTML=NAV.map(([id,icon,label])=>`<button type="button" data-screen="${id}" class="${screen===id?'active':''}"><span>${icon}</span>${label}</button>`).join('');root.querySelectorAll('[data-screen]').forEach(btn=>btn.addEventListener('click',()=>{screen=btn.dataset.screen;setHash(screen);render();scrollTo(0,0)}))}
function render(){try{nav();const views={home,portfolio,market,analysis,ideas,goals,more};document.getElementById('app').innerHTML=(views[screen]||home)();bind();document.getElementById('headerMeta').textContent=`${data.holdings.length} innehav · Clean Foundation · ${VERSION}`}catch(err){bootError=err;renderFatal(err)}}
function renderFatal(err){const app=document.getElementById('app');if(app)app.innerHTML=`<div class="fatal"><b>Mästarklass OS kunde inte visa denna vy.</b><br><small>${esc(err?.message||'Okänt fel')}</small><br><br><button id="safeHome">Öppna säker startsida</button></div>`;document.getElementById('safeHome')?.addEventListener('click',()=>{screen='home';render()})}
function home(){const t=total(),g=safeNum(data.goals.capital)||7500000,p=g?Math.min(100,t/g*100):0;return `<section class="hero"><div class="eyebrow">Mästarklass OS 10.1 · Clean Foundation</div><h2>Mindre brus. Bättre långsiktiga beslut.</h2><p>En säker local-first plattform för kvalitetsbolag, hållbara utdelningar, återinvestering och målstyrt sparande.</p><div class="value">${kr(t)}</div><div class="bar"><i style="width:${p}%"></i></div><small>${p.toFixed(1).replace('.',',')} % av kapitalmålet</small></section><div class="grid"><div class="card metric"><span>Innehav</span><b>${data.holdings.length}</b></div><div class="card metric"><span>Månadssparande</span><b>${kr(data.portfolio.monthly||data.monthlyPlan.total)}</b></div><div class="card metric"><span>Kapitalmål</span><b>${kr(g)}</b></div><div class="card metric"><span>Årligt utdelningsmål</span><b>${kr(data.goals.annualDividend)}</b></div></div><section class="section"><h2>Systemprincip</h2><div class="notice">Ingen tradingmotor. Ingen bankinloggning. Live-data blir ett separat read-only-lager och får aldrig skriva över antal, GAV, transaktioner eller Private Vault.</div></section>`}
function row(name,val,pct,sub=''){return `<div class="row"><div><b>${esc(name)}</b><small>${esc(sub)}</small><div class="bar"><i style="width:${Math.min(100,Math.max(0,pct||0))}%"></i></div></div><b>${val}</b></div>`}
function portfolio(){const hs=[...data.holdings].sort((a,b)=>holdingValue(b)-holdingValue(a)),t=total(),acc=data.accounts||[];return `<div class="chips"><button class="chip" data-jump="overview">Översikt</button><button class="chip" data-jump="accounts">Konton</button><button class="chip" data-jump="holdings">Innehav</button><button class="chip" data-jump="quality">Kvalitet</button><button class="chip" data-jump="action">Från analys till handling</button><button class="chip" data-jump="personal">Personlig intelligens</button></div><section id="overview" class="hero"><div class="eyebrow">Portföljcockpit</div><h2>${kr(t)}</h2><p>${hs.length} innehav i en sammanhängande långsiktig helhet.</p></section><section id="accounts" class="section"><h2>Konton</h2><div class="list">${acc.length?acc.map(a=>row(a.name||a.title,kr(a.value),t?safeNum(a.value)/t*100:0,a.type||a.platform||'')).join(''):'<div class="empty">Konton läses från lokal portföljdata.</div>'}</div></section><section id="holdings" class="section"><h2>Största innehav</h2><div class="list">${hs.length?hs.slice(0,30).map(h=>row(h.name||h.symbol||'Innehav',kr(holdingValue(h)),t?holdingValue(h)/t*100:0,h.account||h.assetType||'')).join(''):'<div class="empty">Ingen lokal portfölj hittades.</div>'}</div></section><section id="quality" class="section"><h2>Kvalitet och datatäckning</h2><div class="grid"><div class="card metric"><span>Datatäckning</span><b>${hs.length?'100':'0'} %</b></div><div class="card metric"><span>Största vikt</span><b>${hs.length&&t?(holdingValue(hs[0])/t*100).toFixed(1).replace('.',','):'0'} %</b></div></div></section><section id="action" class="section"><h2>Från analys till handling</h2><div class="notice">Nästa intelligenslager ska väga kvalitet, värdering, utdelningssäkerhet, riskspridning och målpåverkan innan ett innehav bedöms som Öka, Behåll, Bevaka eller Minska.</div></section><section id="personal" class="section"><h2>Personlig investeringsintelligens</h2><div class="notice">Rekommendationer ska baseras på din verkliga portfölj, dina mål och verifierad live-data — aldrig på kortsiktigt tradingbrus.</div></section>`}
function market(){const live=liveState(),items=data.marketCenter?.items||[];return `<section class="hero"><div class="eyebrow">Live Data Platform</div><h2>Flytande källor. Spårbara värden.</h2><p>Provider Registry, Source Rating och Data Router ska välja bäst godkänd källa per datakategori.</p></section><section class="section"><h2>Källstatus</h2><div class="statusGrid"><div class="status"><span>Portföljdata</span><b class="ok">LOKAL</b></div><div class="status"><span>Live-lager</span><b class="${live.quotes.length?'ok':'wait'}">${live.quotes.length?'AKTIVT':'FÖRBERETT'}</b></div><div class="status"><span>Providers</span><b>${live.providers.length}</b></div><div class="status"><span>Kurser</span><b>${live.quotes.length}</b></div></div></section><section class="section"><h2>Marknadsöversikt</h2><div class="list">${items.length?items.map(x=>row(x.name,String(x.value||'Väntar'),0,x.status||'')).join(''):'<div class="empty">Livekällor kopplas in efter juridisk, teknisk och kvalitetsmässig kontroll.</div>'}</div></section>`}
function analysis(){const hs=data.holdings||[],review=hs.filter(h=>safeNum(h.rating||h.score)>0&&safeNum(h.rating||h.score)<60).length;return `<section class="hero"><div class="eyebrow">Portfolio Intelligence</div><h2>Snabbare mot målen utan onödig risk</h2><p>Intelligensen ska använda lokal portföljdata och verifierat live-underlag för långsiktiga beslut.</p></section><div class="grid"><div class="card metric"><span>Analyserbara innehav</span><b>${hs.length}</b></div><div class="card metric"><span>Behöver granskas</span><b>${review}</b></div></div><section class="section"><h2>Beslutsprinciper</h2><div class="list"><div class="row"><div><b>Kvalitet före maximal direktavkastning</b><small>Utdelningen måste vara hållbar och växande.</small></div></div><div class="row"><div><b>Målpåverkan före magkänsla</b><small>Varje köp ska förbättra helheten.</small></div></div><div class="row"><div><b>Riskkontroll före snabb avkastning</b><small>Ingen impulsdriven trading.</small></div></div></div></section>`}
function ideas(){const arr=[...(data.ideaBank||[]),...(data.aiRadar||[])];return `<section class="hero"><div class="eyebrow">Idébank</div><h2>Idéer som måste förtjäna sin plats</h2><p>Varje idé ska förbättra kvalitet, utdelning, riskspridning eller långsiktig tillväxt.</p></section><section class="section"><div class="list">${arr.length?arr.map(x=>`<div class="card"><h3>${esc(x.title||x.name||'Idé')}</h3><p>${esc(x.text||x.note||'')}</p></div>`).join(''):'<div class="empty">Idébanken är tom.</div>'}</div></section>`}
function goals(){const t=total(),g=safeNum(data.goals.capital)||7500000,d=safeNum(data.goals.annualDividend)||480000,m=safeNum(data.portfolio.monthly||data.monthlyPlan.total);return `<section class="hero"><div class="eyebrow">Målcentral</div><h2>Bygg frihet steg för steg</h2><p>Kapitalmål och utdelningsmål styr sparplan, risknivå och framtida prioriteringar.</p></section><section class="section"><div class="form"><label>Kapitalmål<input id="capitalGoal" type="number" value="${g}"></label><label>Årligt utdelningsmål<input id="dividendGoal" type="number" value="${d}"></label><label>Månadssparande<input id="monthlyGoal" type="number" value="${m}"></label><button class="primary" id="saveGoals">Spara mål lokalt</button></div></section><section class="section"><h2>Framsteg</h2><div class="card"><b>${kr(t)} av ${kr(g)}</b><div class="bar"><i style="width:${g?Math.min(100,t/g*100):0}%"></i></div></div></section>`}
function more(){return `<section class="hero"><div class="eyebrow">Säkerhet & data</div><h2>Du äger din data</h2><p>Ingen bankinloggning, ingen handel och inga API-nycklar i GitHub.</p></section><section class="section"><h2>Backup</h2><div class="list"><button class="primary" id="exportBtn">Exportera lokal backup</button><label class="card">Importera JSON-backup<input id="importFile" type="file" accept="application/json"></label><button id="rescanBtn">Sök efter äldre lokal portfölj</button></div></section><section class="section"><h2>Systemstatus</h2><div class="list"><div class="row"><b>Aktiv version</b><b>${VERSION}</b></div><div class="row"><b>Produktstruktur</b><b>REN</b></div><div class="row"><b>Navigation</b><b>ISOLERAD</b></div><div class="row"><b>Live-data</b><b>READ-ONLY</b></div><div class="row"><b>Bankkoppling</b><b>AV</b></div><div class="row"><b>Handel</b><b>AV</b></div></div></section>`}
function bind(){document.querySelectorAll('[data-jump]').forEach(b=>b.addEventListener('click',()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth',block:'start'})));document.getElementById('saveGoals')?.addEventListener('click',()=>{data.goals.capital=safeNum(document.getElementById('capitalGoal').value);data.goals.annualDividend=safeNum(document.getElementById('dividendGoal').value);data.portfolio.monthly=safeNum(document.getElementById('monthlyGoal').value);save();render();toast('Målen sparades lokalt.')} );document.getElementById('exportBtn')?.addEventListener('click',()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`mastarklass-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),500)});const input=document.getElementById('importFile');if(input)input.addEventListener('change',async()=>{const file=input.files?.[0];if(!file)return;const parsed=parse(await file.text());if(!looksLikePortfolio(parsed)){toast('Filen kunde inte identifieras som en portföljbackup.');return}data=merge(DEFAULTS,parsed);save();render();toast('Backup importerades.')} );document.getElementById('rescanBtn')?.addEventListener('click',()=>{sourceKey=null;data=loadData();render();toast('Lokal data genomsöktes på nytt utan att kopieras.')})}
function toast(message){document.querySelector('.toast')?.remove();const el=document.createElement('div');el.className='toast';el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),2500)}
function boot(){try{data=loadData();const requested=location.hash.slice(1);screen=NAV.some(n=>n[0]===requested)?requested:'home';render();if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js?v='+VERSION).catch(()=>{})}catch(err){bootError=err;renderFatal(err)}}
window.addEventListener('hashchange',()=>{const requested=location.hash.slice(1);if(NAV.some(n=>n[0]===requested)){screen=requested;render();scrollTo(0,0)}});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
