(()=>{'use strict';
const VERSION='10.3.1';
const DATA_KEY='mastarklass_os_10_data';
const LIVE_KEY='mastarklass_os_live_readonly_v1';
const SETTINGS_KEY='mastarklass_os_10_settings';
const ADMIN_KEY='mastarklass_os_10_3_1_admin';
const TX_KEY='mastarklass_os_10_3_transactions';
const NAV=[['home','🏠','Hem'],['portfolio','📊','Portfölj'],['market','🌍','Marknad'],['analysis','🧠','Analys'],['ideas','💡','Idéer'],['goals','🎯','Mål'],['more','☰','Mer']];
const DEFAULTS={portfolio:{net:0,monthly:9000,credit:0},holdings:[],accounts:[],goals:{capital:7500000,annualDividend:480000},monthlyPlan:{total:9000},marketCenter:{items:[]},ideaBank:[],aiRadar:[],reports:[],journal:[]};
const ADMIN_DEFAULT={overrides:{},newHoldings:[],credits:{},audit:[]};
let data=structuredClone(DEFAULTS),admin=structuredClone(ADMIN_DEFAULT),transactions=[],screen='home',sourceKey=null;
let query='',typeFilter='all',accountFilter='all',sortMode='value_desc',portfolioTab='overview';

const parse=x=>{try{return JSON.parse(x)}catch{return null}};
const num=x=>{if(x===null||x===undefined||x==='')return 0;if(typeof x==='number')return Number.isFinite(x)?x:0;const s=String(x).replace(/\s/g,'').replace(/[^\d,.\-]/g,'');if(!s)return 0;const n=Number((s.includes(',')&&s.includes('.'))?s.replace(/\./g,'').replace(',','.'):s.replace(',','.'));return Number.isFinite(n)?n:0};
const text=(o,keys,f='')=>{for(const k of keys){const v=o?.[k];if(v!==undefined&&v!==null&&String(v).trim()!=='')return String(v).trim()}return f};
const nval=(o,keys)=>{for(const k of keys){const v=num(o?.[k]);if(v)return v}return 0};
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const kr=n=>new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0}).format(num(n))+' kr';
const dec=n=>new Intl.NumberFormat('sv-SE',{maximumFractionDigits:4}).format(num(n));
const pct=n=>num(n).toFixed(2).replace('.',',')+' %';
const today=()=>new Date().toISOString().slice(0,10);
function safeGet(k){try{return localStorage.getItem(k)}catch{return null}}
function safeSet(k,v){try{localStorage.setItem(k,v);return true}catch{return false}}
function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={...a};if(b&&typeof b==='object')for(const k of Object.keys(b))o[k]=k in a?merge(a[k],b[k]):b[k];return o}return b??a}
function looksLikePortfolio(x){return !!(x&&typeof x==='object'&&(Array.isArray(x.holdings)||Array.isArray(x.accounts)||num(x.portfolio?.net)>0))}
function score(x){if(!looksLikePortfolio(x))return 0;return (x.holdings?.length||0)*30+(x.accounts?.length||0)*10+Math.min(1000,num(x.portfolio?.net)/500)}
function loadData(){const own=parse(safeGet(DATA_KEY));if(looksLikePortfolio(own)){sourceKey=DATA_KEY;return merge(DEFAULTS,own)}let best=null,bestScore=0,bestKey=null;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(!k||[LIVE_KEY,SETTINGS_KEY,ADMIN_KEY,TX_KEY].includes(k)||/cache|live_readonly/i.test(k))continue;const v=parse(safeGet(k)),s=score(v);if(s>bestScore){best=v;bestScore=s;bestKey=k}}sourceKey=bestKey;return merge(DEFAULTS,best||{})}
function persistAdmin(){if(!safeSet(ADMIN_KEY,JSON.stringify(admin)))alert('Den lokala lagringen är full. Exportera backup innan fler ändringar.')}
function persistTx(){if(!safeSet(TX_KEY,JSON.stringify(transactions)))alert('Den lokala lagringen är full. Exportera backup innan fler transaktioner.')}
function audit(kind,label,before,after){admin.audit.unshift({id:crypto.randomUUID?.()||String(Date.now()),date:new Date().toISOString(),kind,label,before,after});admin.audit=admin.audit.slice(0,250);persistAdmin()}
function liveState(){return parse(safeGet(LIVE_KEY))||{}}
function fxFor(h){const direct=nval(h,['fxToSEK','fxRate','exchangeRate','currencyRate','sekRate']);if(direct)return direct;const cur=text(h,['currency','valuta'],'SEK').toUpperCase();if(cur==='SEK')return 1;const fx=liveState().fx||liveState().rates||{};return num(fx[cur])||num(fx[cur+'SEK'])||num(fx[cur+'/SEK'])||0}
function quoteFor(h){const direct=nval(h,['latestPrice','price','currentPrice','lastPrice','kurs','quote']);if(direct)return direct;const sym=text(h,['symbol','ticker','providerSymbol','isin'],'').toUpperCase(),quotes=liveState().quotes||[];const q=quotes.find(x=>text(x,['symbol','ticker','providerSymbol','isin'],'').toUpperCase()===sym);return q?nval(q,['price','latestPrice','last','value','close']):0}
function quantity(h){return nval(h,['quantity','qty','shares','units','antal','amount'])}
function gav(h){return nval(h,['gav','avgPrice','averagePrice','averageCost','costPrice','anskaffningsvardePerEnhet'])}
function explicitValue(h){return nval(h,['marketValueSEK','marketValueSek','marketValue','currentValue','positionValue','valueSEK','value','marknadsvarde','marknadsvärde'])}
function costValue(h){const direct=nval(h,['costValueSEK','costBasisSEK','investedCapital','purchaseValue','bookValue','anskaffningsvarde','anskaffningsvärde']);if(direct)return direct;const q=quantity(h),g=gav(h),fx=fxFor(h);return q&&g&&fx?q*g*fx:0}
function holdingValue(h){const direct=explicitValue(h);if(direct)return {value:direct,method:'Marknadsvärde'};const q=quantity(h),p=quoteFor(h),fx=fxFor(h);if(q&&p&&fx)return {value:q*p*fx,method:'Kurs × antal'};const c=costValue(h);if(c)return {value:c,method:'Anskaffningsvärde'};return {value:0,method:'Saknar värde'}}
function accountName(h){return text(h,['account','accountName','konto','platform','broker'],'Okänt konto')}
function assetType(h){return text(h,['assetType','type','category','tillgangsslag','tillgångsslag'],'Övrigt')}
function holdingName(h){return text(h,['name','securityName','title','instrumentName','symbol','ticker'],'Innehav')}
function identity(h,i=0){return String(h.id||h.uuid||`${accountName(h)}|${holdingName(h)}|${text(h,['currency','valuta'],'SEK')}|${i}`).toLowerCase()}
function rawHoldings(){return [...(data.holdings||[]).map((h,i)=>({...h,_baseIndex:i,_key:identity(h,i)})),...(admin.newHoldings||[]).map((h,i)=>({...h,_newIndex:i,_key:h._key||identity(h,'new'+i)}))]}
function canonicalHoldings(){return rawHoldings().map((base,i)=>{const h={...base,...(admin.overrides[base._key]||{})};const r=holdingValue(h);return {...h,_i:i,_value:r.value,_method:r.method,_name:holdingName(h),_account:accountName(h),_type:assetType(h),_qty:quantity(h),_gav:gav(h),_fx:fxFor(h),_quote:quoteFor(h)}})}
function declaredTotal(){return nval(data.portfolio||{},['net','total','totalValue','marketValue','value'])||(data.accounts||[]).reduce((s,a)=>s+nval(a,['value','marketValue','totalValue','balance']),0)}
function calculatedTotal(){return canonicalHoldings().reduce((s,h)=>s+h._value,0)}
function total(){return declaredTotal()||calculatedTotal()}
function diagnostics(){const hs=canonicalHoldings(),declared=declaredTotal(),calc=calculatedTotal(),unresolved=hs.filter(h=>!h._value);return {declared,calc,diff:declared?declared-calc:0,unresolved,missingGav:hs.filter(h=>!h._gav).length,missingQty:hs.filter(h=>!h._qty).length}}
function nav(){const r=document.getElementById('nav');r.innerHTML=NAV.map(([id,icon,label])=>`<button data-screen="${id}" class="${screen===id?'active':''}"><span>${icon}</span>${label}</button>`).join('');r.querySelectorAll('button').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;location.hash=screen;render();scrollTo(0,0)})}
function row(h,t){return `<button class="holdingRow" data-index="${h._i}"><div><b>${esc(h._name)}</b><small>${esc(h._account)} · ${esc(h._type)}</small><div class="bar"><i style="width:${t?Math.min(100,h._value/t*100):0}%"></i></div></div><div class="right"><b>${kr(h._value)}</b><small>${t?pct(h._value/t*100):'0,00 %'}</small><em>${esc(h._method)}</em></div></button>`}
function home(){const t=total(),goal=num(data.goals?.capital)||7500000,p=goal?t/goal*100:0,d=diagnostics();return `<section class="hero"><div class="eyebrow">Mästarklass OS 10.3.1 · Administration Layer</div><h2>En portfölj. En sanning.</h2><p>Innehav, direktkorrigeringar, transaktioner och kredit samlas i samma local-first system.</p><div class="value">${kr(t)}</div><div class="bar"><i style="width:${Math.min(100,p)}%"></i></div><small>${pct(p)} av kapitalmålet</small></section><div class="grid"><div class="card metric"><span>Innehav</span><b>${canonicalHoldings().length}</b></div><div class="card metric"><span>Transaktioner</span><b>${transactions.length}</b></div><div class="card metric"><span>Direktändringar</span><b>${admin.audit.length}</b></div><div class="card metric"><span>Kredit utnyttjad</span><b>${kr(Object.values(admin.credits||{}).reduce((s,x)=>s+num(x.used),0))}</b></div></div>`}
function chips(){const tabs=[['overview','Översikt'],['accounts','Konton'],['holdings','Alla innehav'],['transactions','Transaktioner'],['admin','Administrera'],['quality','Datakvalitet']];return `<div class="chips">${tabs.map(([id,l])=>`<button data-tab="${id}" class="${portfolioTab===id?'activeChip':''}">${l}</button>`).join('')}</div>`}
function portfolio(){const all=canonicalHoldings(),t=total(),q=query.toLowerCase(),types=[...new Set(all.map(h=>h._type))].sort((a,b)=>a.localeCompare(b,'sv')),accounts=[...new Set(all.map(h=>h._account))].sort((a,b)=>a.localeCompare(b,'sv'));let hs=all.filter(h=>(typeFilter==='all'||h._type===typeFilter)&&(accountFilter==='all'||h._account===accountFilter)&&(!q||`${h._name} ${h._account} ${h._type}`.toLowerCase().includes(q)));const sorts={value_desc:(a,b)=>b._value-a._value,value_asc:(a,b)=>a._value-b._value,name_asc:(a,b)=>a._name.localeCompare(b._name,'sv'),name_desc:(a,b)=>b._name.localeCompare(a._name,'sv')};hs.sort(sorts[sortMode]);const d=diagnostics(),accountMap=new Map();all.forEach(h=>accountMap.set(h._account,(accountMap.get(h._account)||0)+h._value));let content='';
 if(portfolioTab==='overview')content=`<section class="hero"><div class="eyebrow">Portfolio Administration 10.3.1</div><h2>${kr(t)}</h2><p>${all.length} innehav · ${transactions.length} transaktioner · ${admin.audit.length} spårade korrigeringar.</p></section><div class="grid"><button class="card actionCard" data-tabgo="transactions"><b>Registrera köp/sälj</b><span>Uppdatera antal och viktat GAV.</span></button><button class="card actionCard" data-tabgo="admin"><b>Administrera portfölj</b><span>Ändra GAV, antal, nya innehav och kredit.</span></button></div>`;
 if(portfolioTab==='accounts')content=`<section class="section"><h2>Konton</h2><div class="list">${[...accountMap.entries()].sort((a,b)=>b[1]-a[1]).map(([n,v])=>`<div class="simpleRow"><div><b>${esc(n)}</b><small>${pct(t?v/t*100:0)}</small></div><b>${kr(v)}</b></div>`).join('')}</div></section>`;
 if(portfolioTab==='holdings')content=`<section class="section"><div class="sectionHead"><h2>Alla innehav</h2><small>${hs.length} av ${all.length}</small></div><div class="tools"><input id="search" type="search" value="${esc(query)}" placeholder="Sök innehav eller konto"><select id="typeFilter"><option value="all">Alla tillgångsslag</option>${types.map(x=>`<option ${x===typeFilter?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="accountFilter"><option value="all">Alla konton</option>${accounts.map(x=>`<option ${x===accountFilter?'selected':''}>${esc(x)}</option>`).join('')}</select><select id="sortMode"><option value="value_desc">Störst värde</option><option value="value_asc" ${sortMode==='value_asc'?'selected':''}>Minst värde</option><option value="name_asc" ${sortMode==='name_asc'?'selected':''}>Namn A–Ö</option><option value="name_desc" ${sortMode==='name_desc'?'selected':''}>Namn Ö–A</option></select></div><div class="list">${hs.map(h=>row(h,t)).join('')}</div></section>`;
 if(portfolioTab==='transactions')content=transactionSection(all);
 if(portfolioTab==='admin')content=adminSection(all,accounts);
 if(portfolioTab==='quality')content=`<section class="section"><h2>Datakvalitet och avstämning</h2><div class="grid"><div class="card metric"><span>Deklarerad bas</span><b>${kr(d.declared)}</b></div><div class="card metric"><span>Beräknat nu</span><b>${kr(d.calc)}</b></div><div class="card metric"><span>Differens</span><b>${kr(d.diff)}</b></div><div class="card metric"><span>Saknar värde</span><b>${d.unresolved.length}</b></div></div>${d.unresolved.length?`<div class="warning"><b>Poster som behöver kurs eller värde</b><p>${d.unresolved.slice(0,30).map(h=>esc(h._name)).join(', ')}${d.unresolved.length>30?' …':''}</p></div>`:`<div class="notice okbox">Samtliga innehav har ett spårbart värde.</div>`}</section>`;
 return chips()+content+`<div id="modal" class="modal hidden"><div class="modalCard"><button id="closeModal" class="modalClose">×</button><div id="modalBody"></div></div></div>`}
function transactionSection(all){const opts=all.map(h=>`<option value="${esc(h._key)}">${esc(h._name)} — ${esc(h._account)}</option>`).join('');return `<section class="section"><div class="eyebrow">Transaction Engine</div><h2>Registrera köp eller sälj</h2><div class="form twoCol"><label>Typ<select id="txType"><option value="buy">Köp</option><option value="sell">Sälj</option></select></label><label>Datum<input id="txDate" type="date" value="${today()}"></label><label>Värdepapper<select id="txHolding">${opts}</select></label><label>Antal<input id="txQty" inputmode="decimal" placeholder="0"></label><label>Pris per enhet<input id="txPrice" inputmode="decimal" placeholder="0,00"></label><label>Courtage<input id="txFee" inputmode="decimal" value="0"></label><label>Valuta<input id="txCurrency" value="SEK"></label><label>Valutakurs till SEK<input id="txFx" inputmode="decimal" value="1"></label></div><button id="saveTx" class="primary">Spara transaktion lokalt</button></section><section class="section"><h2>Historik</h2><div class="list">${transactions.length?transactions.map(x=>`<div class="simpleRow"><div><b>${x.type==='buy'?'Köp':'Sälj'} · ${esc(x.name)}</b><small>${esc(x.date)} · ${dec(x.quantity)} st · ${dec(x.price)} ${esc(x.currency)} · courtage ${dec(x.fee)}</small></div><button class="danger smallBtn" data-delete-tx="${esc(x.id)}">Radera</button></div>`).join(''):'<div class="empty">Inga transaktioner registrerade ännu.</div>'}</div></section>`}
function adminSection(all,accounts){const creditNames=[...new Set([...accounts,...Object.keys(admin.credits||{})])];return `<section class="hero"><div class="eyebrow">Master Data</div><h2>Direktkorrigering utan falsk transaktion</h2><p>Använd detta för startvärden, rättning av GAV/antal, nya värdepapper och kredit. Alla ändringar loggas.</p></section><section class="section"><h2>Redigera befintligt innehav</h2><label class="formLabel">Välj innehav<select id="adminHolding">${all.map(h=>`<option value="${esc(h._key)}">${esc(h._name)} — ${esc(h._account)}</option>`).join('')}</select></label><button id="openEdit" class="primary">Öppna redigering</button></section><section class="section"><h2>Lägg till värdepapper</h2><div class="form twoCol"><label>Namn<input id="newName"></label><label>Konto<input id="newAccount" list="accountList"></label><label>Tillgångsslag<input id="newType" value="Aktie"></label><label>Valuta<input id="newCurrency" value="SEK"></label><label>Antal<input id="newQty" inputmode="decimal"></label><label>GAV<input id="newGav" inputmode="decimal"></label><label>Ticker<input id="newTicker"></label><label>Marknadsvärde SEK<input id="newValue" inputmode="decimal"></label></div><datalist id="accountList">${accounts.map(x=>`<option>${esc(x)}</option>`).join('')}</datalist><button id="addHolding" class="primary">Lägg till utan transaktion</button></section><section class="section"><h2>Investeringskredit</h2><div class="form twoCol"><label>Konto<input id="creditAccount" list="accountList"></label><label>Kreditlimit<input id="creditLimit" inputmode="decimal"></label><label>Utnyttjad kredit<input id="creditUsed" inputmode="decimal"></label><label>Ränta %<input id="creditRate" inputmode="decimal"></label></div><button id="saveCredit" class="primary">Spara kredit lokalt</button><div class="list topGap">${creditNames.length?creditNames.map(n=>{const c=admin.credits[n]||{};return `<div class="simpleRow"><div><b>${esc(n)}</b><small>Limit ${kr(c.limit)} · Ränta ${pct(c.rate)}</small></div><b>${kr(c.used)}</b></div>`}).join(''):'<div class="empty">Ingen kredit registrerad.</div>'}</div></section><section class="section"><div class="sectionHead"><h2>Ändringslogg</h2><button id="undoAudit" class="secondary" ${admin.audit.length?'':'disabled'}>Ångra senaste</button></div><div class="list">${admin.audit.slice(0,20).map(x=>`<div class="auditRow"><b>${esc(x.label)}</b><small>${new Date(x.date).toLocaleString('sv-SE')} · ${esc(x.kind)}</small></div>`).join('')||'<div class="empty">Inga direktändringar ännu.</div>'}</div></section>`}
function market(){const l=liveState();return `<section class="hero"><div class="eyebrow">Live Data Platform</div><h2>Flytande källor. Spårbara värden.</h2><p>Live-lagret är read-only och får aldrig skriva över antal, GAV, kredit eller transaktioner.</p></section><div class="grid"><div class="card metric"><span>Providers</span><b>${(l.providers||[]).length}</b></div><div class="card metric"><span>Kurser</span><b>${(l.quotes||[]).length}</b></div></div>`}
function analysis(){const d=diagnostics();return `<section class="hero"><div class="eyebrow">Portfolio Intelligence</div><h2>Rätt masterdata före rekommendationer</h2><p>10.3.1 ger intelligensmotorn spårbara antal, GAV, transaktioner och kreditdata.</p></section><div class="grid"><div class="card metric"><span>Analyserbara</span><b>${canonicalHoldings().length-d.unresolved.length}</b></div><div class="card metric"><span>Behöver data</span><b>${d.unresolved.length}</b></div><div class="card metric"><span>Transaktioner</span><b>${transactions.length}</b></div><div class="card metric"><span>Kreditkonton</span><b>${Object.keys(admin.credits||{}).length}</b></div></div>`}
function ideas(){const a=[...(data.ideaBank||[]),...(data.aiRadar||[])];return `<section class="hero"><div class="eyebrow">Idébank</div><h2>Idéer som måste förtjäna sin plats</h2></section><div class="list">${a.map(x=>`<div class="card"><h3>${esc(x.title||x.name||'Idé')}</h3><p>${esc(x.text||x.note||'')}</p></div>`).join('')||'<div class="empty">Idébanken är tom.</div>'}</div>`}
function goals(){return `<section class="hero"><div class="eyebrow">Målcentral</div><h2>Bygg frihet steg för steg</h2></section><div class="card form"><label>Kapitalmål<input id="capitalGoal" inputmode="numeric" value="${num(data.goals.capital)}"></label><label>Årligt utdelningsmål<input id="divGoal" inputmode="numeric" value="${num(data.goals.annualDividend)}"></label><label>Månadssparande<input id="monthly" inputmode="numeric" value="${num(data.portfolio.monthly||data.monthlyPlan.total)}"></label><button id="saveGoals" class="primary">Spara mål lokalt</button></div>`}
function more(){return `<section class="hero"><div class="eyebrow">Säkerhet & data</div><h2>Du äger din data</h2><p>Backupen innehåller basportfölj, administrationslager, kredit och transaktioner.</p></section><div class="card"><h2>Full lokal backup</h2><button id="exportBtn" class="primary">Exportera full backup</button><label class="file">Importera JSON-backup<input id="importFile" type="file" accept=".json,application/json"></label><p><small>Datakälla: ${esc(sourceKey||'ingen lokal portfölj hittad')}</small></p></div>`}
function showHolding(i){const h=canonicalHoldings().find(x=>x._i===i),t=total();if(!h)return;openModal(`<div class="eyebrow">Innehavsdetalj</div><h2>${esc(h._name)}</h2><div class="grid"><div class="card metric"><span>Konto</span><b>${esc(h._account)}</b></div><div class="card metric"><span>Tillgångsslag</span><b>${esc(h._type)}</b></div><div class="card metric"><span>Antal</span><b>${dec(h._qty)||'—'}</b></div><div class="card metric"><span>GAV</span><b>${dec(h._gav)||'—'}</b></div><div class="card metric"><span>Marknadsvärde</span><b>${kr(h._value)}</b></div><div class="card metric"><span>Portföljvikt</span><b>${pct(t?h._value/t*100:0)}</b></div><div class="card metric"><span>Valuta</span><b>${esc(text(h,['currency','valuta'],'SEK'))}</b></div><div class="card metric"><span>Värdemetod</span><b>${esc(h._method)}</b></div></div><button class="primary" data-edit-key="${esc(h._key)}">Redigera innehav</button><button class="secondary topGap" data-tx-key="${esc(h._key)}">Registrera köp/sälj</button>`)}
function openModal(html){const body=document.getElementById('modalBody'),modal=document.getElementById('modal');if(!body||!modal)return;body.innerHTML=html;modal.classList.remove('hidden');bindModal()}
function editHolding(key){const h=canonicalHoldings().find(x=>x._key===key);if(!h)return;openModal(`<div class="eyebrow">Portfolio Administration</div><h2>${esc(h._name)}</h2><div class="form twoCol"><label>Namn<input id="editName" value="${esc(h._name)}"></label><label>Konto<input id="editAccount" value="${esc(h._account)}"></label><label>Tillgångsslag<input id="editType" value="${esc(h._type)}"></label><label>Valuta<input id="editCurrency" value="${esc(text(h,['currency','valuta'],'SEK'))}"></label><label>Antal<input id="editQty" inputmode="decimal" value="${h._qty||''}"></label><label>GAV<input id="editGav" inputmode="decimal" value="${h._gav||''}"></label><label>Ticker<input id="editTicker" value="${esc(text(h,['ticker','symbol'],'') )}"></label><label>Marknadsvärde SEK<input id="editValue" inputmode="decimal" value="${explicitValue(h)||''}"></label></div><button id="saveEdit" class="primary" data-key="${esc(key)}">Spara direktkorrigering</button><p class="hint">Detta skapar ingen köp- eller säljtransaktion. Ändringen loggas och kan ångras.</p>`)}
function saveEdit(key){const h=canonicalHoldings().find(x=>x._key===key);if(!h)return;const before=admin.overrides[key]?{...admin.overrides[key]}:null;const after={name:document.getElementById('editName').value.trim(),account:document.getElementById('editAccount').value.trim(),assetType:document.getElementById('editType').value.trim(),currency:document.getElementById('editCurrency').value.trim().toUpperCase(),quantity:num(document.getElementById('editQty').value),gav:num(document.getElementById('editGav').value),ticker:document.getElementById('editTicker').value.trim(),marketValueSEK:num(document.getElementById('editValue').value)};admin.overrides[key]=after;audit('holding-edit',`Redigerade ${h._name}`,{key,value:before},{key,value:after});persistAdmin();closeModal();render()}
function addHolding(){const h={_key:'new-'+Date.now(),name:document.getElementById('newName').value.trim(),account:document.getElementById('newAccount').value.trim()||'Okänt konto',assetType:document.getElementById('newType').value.trim()||'Övrigt',currency:document.getElementById('newCurrency').value.trim().toUpperCase()||'SEK',quantity:num(document.getElementById('newQty').value),gav:num(document.getElementById('newGav').value),ticker:document.getElementById('newTicker').value.trim(),marketValueSEK:num(document.getElementById('newValue').value)};if(!h.name)return alert('Ange värdepapprets namn.');admin.newHoldings.push(h);audit('holding-add',`Lade till ${h.name}`,null,{key:h._key,value:h});persistAdmin();render()}
function saveCredit(){const account=document.getElementById('creditAccount').value.trim();if(!account)return alert('Ange konto.');const before=admin.credits[account]?{...admin.credits[account]}:null,after={limit:num(document.getElementById('creditLimit').value),used:num(document.getElementById('creditUsed').value),rate:num(document.getElementById('creditRate').value)};admin.credits[account]=after;audit('credit-edit',`Kredit ${account}`,{account,value:before},{account,value:after});persistAdmin();render()}
function saveTransaction(){const key=document.getElementById('txHolding').value,h=canonicalHoldings().find(x=>x._key===key);if(!h)return;const type=document.getElementById('txType').value,q=num(document.getElementById('txQty').value),price=num(document.getElementById('txPrice').value),fee=num(document.getElementById('txFee').value),currency=document.getElementById('txCurrency').value.trim().toUpperCase()||text(h,['currency'],'SEK'),fx=num(document.getElementById('txFx').value)||1;if(q<=0||price<0)return alert('Ange ett giltigt antal och pris.');const oldQ=h._qty,oldG=h._gav;let newQ=oldQ,newG=oldG;if(type==='buy'){newQ=oldQ+q;newG=newQ?((oldQ*oldG)+(q*price)+(fee/fx))/newQ:price}else{if(q>oldQ)return alert('Du kan inte sälja fler enheter än innehavet innehåller.');newQ=oldQ-q;newG=newQ?oldG:0}const before=admin.overrides[key]?{...admin.overrides[key]}:null;admin.overrides[key]={...(admin.overrides[key]||{}),quantity:newQ,gav:newG,currency};const tx={id:'tx-'+Date.now(),type,date:document.getElementById('txDate').value||today(),key,name:h._name,account:h._account,quantity:q,price,fee,currency,fx,previousQuantity:oldQ,previousGav:oldG,newQuantity:newQ,newGav:newG,overrideBefore:before};transactions.unshift(tx);persistTx();audit('transaction',`${type==='buy'?'Köp':'Sälj'} ${h._name}`,null,{txId:tx.id});persistAdmin();render()}
function deleteTransaction(id){const tx=transactions.find(x=>x.id===id);if(!tx||!confirm('Radera transaktionen och återställ antal/GAV till läget före den?'))return;if(tx.overrideBefore)admin.overrides[tx.key]=tx.overrideBefore;else delete admin.overrides[tx.key];transactions=transactions.filter(x=>x.id!==id);persistTx();audit('transaction-delete',`Raderade transaktion ${tx.name}`,null,{id});persistAdmin();render()}
function undoLast(){const x=admin.audit[0];if(!x)return;if(!confirm(`Ångra senaste ändringen: ${x.label}?`))return;if(x.kind==='holding-edit'){if(x.before?.value)admin.overrides[x.before.key]=x.before.value;else delete admin.overrides[x.after.key]}else if(x.kind==='holding-add'){admin.newHoldings=admin.newHoldings.filter(h=>h._key!==x.after.key)}else if(x.kind==='credit-edit'){if(x.before?.value)admin.credits[x.before.account]=x.before.value;else delete admin.credits[x.after.account]}else return alert('Denna loggpost ångras via transaktionshistoriken.');admin.audit.shift();persistAdmin();render()}
function closeModal(){document.getElementById('modal')?.classList.add('hidden')}
function bindModal(){document.getElementById('closeModal')?.addEventListener('click',closeModal);document.querySelector('[data-edit-key]')?.addEventListener('click',e=>editHolding(e.currentTarget.dataset.editKey));document.querySelector('[data-tx-key]')?.addEventListener('click',e=>{portfolioTab='transactions';closeModal();render();setTimeout(()=>{const sel=document.getElementById('txHolding');if(sel)sel.value=e.currentTarget.dataset.txKey},0)});document.getElementById('saveEdit')?.addEventListener('click',e=>saveEdit(e.currentTarget.dataset.key))}
function bind(){document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{portfolioTab=b.dataset.tab;render();scrollTo(0,0)});document.querySelectorAll('[data-tabgo]').forEach(b=>b.onclick=()=>{portfolioTab=b.dataset.tabgo;render();scrollTo(0,0)});const s=document.getElementById('search');if(s)s.oninput=e=>{query=e.target.value;render()};const tf=document.getElementById('typeFilter');if(tf)tf.onchange=e=>{typeFilter=e.target.value;render()};const af=document.getElementById('accountFilter');if(af)af.onchange=e=>{accountFilter=e.target.value;render()};const sm=document.getElementById('sortMode');if(sm)sm.onchange=e=>{sortMode=e.target.value;render()};document.querySelectorAll('[data-index]').forEach(b=>b.onclick=()=>showHolding(Number(b.dataset.index)));document.getElementById('closeModal')?.addEventListener('click',closeModal);document.getElementById('openEdit')?.addEventListener('click',()=>editHolding(document.getElementById('adminHolding').value));document.getElementById('addHolding')?.addEventListener('click',addHolding);document.getElementById('saveCredit')?.addEventListener('click',saveCredit);document.getElementById('saveTx')?.addEventListener('click',saveTransaction);document.querySelectorAll('[data-delete-tx]').forEach(b=>b.onclick=()=>deleteTransaction(b.dataset.deleteTx));document.getElementById('undoAudit')?.addEventListener('click',undoLast);const sg=document.getElementById('saveGoals');if(sg)sg.onclick=()=>{data.goals.capital=num(document.getElementById('capitalGoal').value);data.goals.annualDividend=num(document.getElementById('divGoal').value);data.portfolio.monthly=num(document.getElementById('monthly').value);safeSet(SETTINGS_KEY,JSON.stringify({goals:data.goals,portfolio:{monthly:data.portfolio.monthly}}));render()};const ex=document.getElementById('exportBtn');if(ex)ex.onclick=()=>{const payload={version:VERSION,exportedAt:new Date().toISOString(),sourceKey,data,admin,transactions};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='mastarklass-os-full-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};const im=document.getElementById('importFile');if(im)im.onchange=async e=>{const f=e.target.files?.[0];if(!f)return;const x=parse(await f.text());if(!x)return alert('Filen kunde inte läsas.');if(x.data&&looksLikePortfolio(x.data))safeSet(DATA_KEY,JSON.stringify(x.data));if(x.admin)safeSet(ADMIN_KEY,JSON.stringify(x.admin));if(x.transactions)safeSet(TX_KEY,JSON.stringify(x.transactions));location.reload()}}
function render(){nav();const views={home,portfolio,market,analysis,ideas,goals,more};document.getElementById('app').innerHTML=(views[screen]||home)();document.getElementById('headerMeta').textContent=`${canonicalHoldings().length} innehav · Administration Layer · ${VERSION}`;bind()}
async function boot(){data=loadData();admin=merge(ADMIN_DEFAULT,parse(safeGet(ADMIN_KEY))||{});transactions=parse(safeGet(TX_KEY))||[];const settings=parse(safeGet(SETTINGS_KEY));if(settings?.goals)data.goals=merge(data.goals,settings.goals);if(settings?.portfolio)data.portfolio=merge(data.portfolio,settings.portfolio);screen=(location.hash.slice(1)||'home');if(!NAV.some(x=>x[0]===screen))screen='home';if('serviceWorker'in navigator)try{await navigator.serviceWorker.register('sw.js?v='+VERSION)}catch(e){console.warn(e)}render()}
boot();
})();
