(()=>{'use strict';
const VERSION='10.0.0',KEY='mastarklass_os_10_data',LEGACY=['mastarklass_os_9_7_0_ui_only','mastarklass_os_data','mastarklass_data'];
const NAV=[['home','🏠','Hem'],['portfolio','📊','Portfölj'],['market','🌍','Marknad'],['analysis','🧠','Analys'],['ideas','💡','Idéer'],['goals','🎯','Mål'],['more','☰','Mer']];
const blank={portfolio:{net:0,monthly:8500,credit:0},holdings:[],accounts:[],goals:{capital:7500000,annualDividend:480000},monthlyPlan:{total:8500},marketCenter:{items:[]},ideaBank:[],aiRadar:[],reports:[],journal:[],meta:{updated:new Date().toISOString().slice(0,10)}};
let data=loadData(),screen='home';
function parse(x){try{return JSON.parse(x)}catch{return null}}
function candidateScore(x){if(!x||typeof x!=='object')return 0;return (x.holdings?.length||0)*10+(x.accounts?.length||0)*5+(Number(x.portfolio?.net)||0)/1000}
function loadData(){const own=parse(localStorage.getItem(KEY));if(own)return merge(blank,own);let best=null,bestScore=0;for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i),v=parse(localStorage.getItem(k));const s=candidateScore(v);if(s>bestScore){best=v;bestScore=s}}for(const k of LEGACY){const v=parse(localStorage.getItem(k)),s=candidateScore(v);if(s>bestScore){best=v;bestScore=s}}const out=merge(blank,best||{});localStorage.setItem(KEY,JSON.stringify(out));return out}
function merge(a,b){if(Array.isArray(a))return Array.isArray(b)?b:a;if(a&&typeof a==='object'){const o={...a};for(const k in b)o[k]=k in a?merge(a[k],b[k]):b[k];return o}return b??a}
const kr=n=>new Intl.NumberFormat('sv-SE',{maximumFractionDigits:0}).format(Number(n)||0)+' kr';
function value(h){return Number(h.marketValue??h.value??h.currentValue??h.costBasis??0)||0}
function total(){const hv=data.holdings.reduce((s,h)=>s+value(h),0);return Number(data.portfolio?.net)||hv||data.accounts.reduce((s,a)=>s+(Number(a.value)||0),0)}
function nav(){document.getElementById('nav').innerHTML=NAV.map(([id,ic,l])=>`<button data-screen="${id}" class="${screen===id?'active':''}"><span>${ic}</span>${l}</button>`).join('');document.querySelectorAll('[data-screen]').forEach(b=>b.onclick=()=>{screen=b.dataset.screen;render();scrollTo(0,0)})}
function render(){nav();const app=document.getElementById('app');app.innerHTML=({home,portfolio,market,analysis,ideas,goals,more}[screen]||home)();bind();document.getElementById('headerMeta').textContent=`${data.holdings.length} innehav · Stable Foundation · ${VERSION}`}
function home(){const t=total(),g=Number(data.goals.capital)||7500000,p=Math.min(100,t/g*100);return `<section class="hero"><div class="eyebrow">Mästarklass OS 10.0 · stabil grund</div><h2>Mindre brus. Bättre beslut.</h2><p>En sammanhängande plattform för långsiktigt sparande, kvalitet, hållbara utdelningar och återinvestering.</p><div class="value">${kr(t)}</div><div class="bar"><i style="width:${p}%"></i></div><small>${p.toFixed(1).replace('.',',')} % av kapitalmålet</small></section><div class="grid"><div class="card metric"><span>Innehav</span><b>${data.holdings.length}</b></div><div class="card metric"><span>Månadssparande</span><b>${kr(data.portfolio.monthly||data.monthlyPlan.total)}</b></div><div class="card metric"><span>Kapitalmål</span><b>${kr(g)}</b></div><div class="card metric"><span>Årligt utdelningsmål</span><b>${kr(data.goals.annualDividend)}</b></div></div><section class="section"><h2>Dagens fokus</h2><div class="notice">Bygg vidare på kvalitet och utdelningskapacitet. Live-data hålls read-only och får aldrig ändra antal, GAV eller transaktioner.</div></section>`}
function portfolio(){const hs=[...data.holdings].sort((a,b)=>value(b)-value(a)),t=total();const acc=data.accounts||[];return `<div class="chips"><button class="chip active" data-jump="top">Översikt</button><button class="chip" data-jump="accounts">Konton</button><button class="chip" data-jump="holdings">Innehav</button><button class="chip" data-jump="quality">Kvalitet</button></div><section id="top" class="hero"><div class="eyebrow">Portföljcockpit</div><h2>${kr(t)}</h2><p>${hs.length} innehav samlade i en långsiktig helhet.</p></section><section id="accounts" class="section"><h2>Konton</h2><div class="list">${acc.length?acc.map(a=>row(a.name||a.title,kr(a.value),t?((Number(a.value)||0)/t*100):0)).join(''):'<div class="empty">Konton läses in från din lokala portföljdata.</div>'}</div></section><section id="holdings" class="section"><h2>Största innehav</h2><div class="list">${hs.length?hs.slice(0,25).map(h=>row(h.name||h.symbol||'Innehav',kr(value(h)),t?value(h)/t*100:0,h.account||h.assetType)).join(''):'<div class="empty">Ingen lokal portfölj hittades. Öppna Mer → Importera backup.</div>'}</div></section><section id="quality" class="section"><h2>Kvalitetsöversikt</h2><div class="grid"><div class="card metric"><span>Datatäckning</span><b>${hs.length?'100':'0'} %</b></div><div class="card metric"><span>Största vikt</span><b>${hs.length&&t?(value(hs[0])/t*100).toFixed(1).replace('.',','):'0'} %</b></div></div></section>`}
function row(name,val,pct,sub=''){return `<div class="row"><div><b>${esc(name)}</b><small>${esc(sub||'')}</small><div class="bar"><i style="width:${Math.min(100,pct||0)}%"></i></div></div><b>${val}</b></div>`}
function market(){const items=data.marketCenter?.items||[];return `<section class="hero"><div class="eyebrow">Market Intelligence</div><h2>Marknad utan tradingbrus</h2><p>Live-data visas som beslutsstöd och hålls separat från den privata portföljen.</p></section><section class="section"><h2>Källstatus</h2><div class="grid"><div class="card metric"><span>Portföljdata</span><b>LOKAL</b></div><div class="card metric"><span>Extern live-data</span><b>READ-ONLY</b></div></div></section><section class="section"><h2>Marknadsöversikt</h2><div class="list">${items.length?items.map(x=>row(x.name,String(x.value||'Väntar'),0,x.status)).join(''):'<div class="empty">Marknadskällor kopplas in stegvis efter källkontroll.</div>'}</div></section>`}
function analysis(){const hs=data.holdings||[],risk=hs.filter(h=>Number(h.rating||h.score||0)<60).length;return `<section class="hero"><div class="eyebrow">Investment Intelligence</div><h2>Från analys till handling</h2><p>Prioriterar kvalitet, riskspridning, hållbar utdelning och långsiktig passform.</p></section><div class="grid"><div class="card metric"><span>Analyserade</span><b>${hs.length}</b></div><div class="card metric"><span>Granska</span><b>${risk}</b></div></div><section class="section"><h2>Principer</h2><div class="list"><div class="row"><div><b>Kvalitet före hög direktavkastning</b><small>Utdelningen ska vara hållbar.</small></div></div><div class="row"><div><b>Återinvestera metodiskt</b><small>Prioritera kärninnehav och ETF-bas.</small></div></div><div class="row"><div><b>Ingen impulsdriven trading</b><small>Beslut ska passa manifestet.</small></div></div></div></section>`}
function ideas(){const arr=[...(data.ideaBank||[]),...(data.aiRadar||[])];return `<section class="hero"><div class="eyebrow">Idébank</div><h2>Idéer som måste förtjäna sin plats</h2><p>Varje idé ska förbättra kvalitet, utdelning, riskspridning eller långsiktig tillväxt.</p></section><section class="section"><div class="list">${arr.length?arr.map(x=>`<div class="card"><h3>${esc(x.title||x.name||'Idé')}</h3><p>${esc(x.text||x.note||'')}</p></div>`).join(''):'<div class="empty">Idébanken är tom.</div>'}</div></section>`}
function goals(){const t=total(),g=Number(data.goals.capital)||7500000,d=Number(data.goals.annualDividend)||480000;return `<section class="hero"><div class="eyebrow">Målcentral</div><h2>Bygg frihet steg för steg</h2><p>Kapitalmål och utdelningsmål styrs av långsiktigt månadssparande och återinvestering.</p></section><section class="section"><div class="form"><label>Kapitalmål<input id="capitalGoal" type="number" value="${g}"></label><label>Årligt utdelningsmål<input id="dividendGoal" type="number" value="${d}"></label><label>Månadssparande<input id="monthlyGoal" type="number" value="${Number(data.portfolio.monthly||data.monthlyPlan.total)||0}"></label><button class="primary" id="saveGoals">Spara mål lokalt</button></div></section><section class="section"><h2>Framsteg</h2><div class="card"><b>${kr(t)} av ${kr(g)}</b><div class="bar"><i style="width:${Math.min(100,t/g*100)}%"></i></div></div></section>`}
function more(){return `<section class="hero"><div class="eyebrow">Säkerhet & data</div><h2>Du äger din data</h2><p>Ingen bankinloggning, ingen handel och inga API-nycklar i GitHub. Portföljdata stannar lokalt.</p></section><section class="section"><h2>Backup</h2><div class="list"><button class="primary" id="exportBtn">Exportera lokal backup</button><label class="card">Importera JSON-backup<input id="importFile" type="file" accept="application/json" style="margin-top:12px"></label><button id="rescanBtn">Sök efter äldre lokal portfölj</button></div></section><section class="section"><h2>Systemstatus</h2><div class="list"><div class="row"><b>Aktiv version</b><b>${VERSION}</b></div><div class="row"><b>Navigation</b><b>ISOLERAD</b></div><div class="row"><b>Service Worker</b><b>10.0</b></div><div class="row"><b>Bankkoppling</b><b>AV</b></div><div class="row"><b>Handel</b><b>AV</b></div></div></section>`}
function bind(){document.querySelectorAll('[data-jump]').forEach(b=>b.onclick=()=>document.getElementById(b.dataset.jump)?.scrollIntoView({behavior:'smooth'}));const sg=document.getElementById('saveGoals');if(sg)sg.onclick=()=>{data.goals.capital=+capitalGoal.value||0;data.goals.annualDividend=+dividendGoal.value||0;data.portfolio.monthly=+monthlyGoal.value||0;save();render()};const ex=document.getElementById('exportBtn');if(ex)ex.onclick=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}));a.download=`mastarklass-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();URL.revokeObjectURL(a.href)};const im=document.getElementById('importFile');if(im)im.onchange=async()=>{const f=im.files[0];if(!f)return;const x=parse(await f.text());if(!x)return alert('Filen kunde inte läsas.');data=merge(blank,x);save();render()};const rs=document.getElementById('rescanBtn');if(rs)rs.onclick=()=>{localStorage.removeItem(KEY);data=loadData();render()}}
function save(){localStorage.setItem(KEY,JSON.stringify(data))}
function esc(x){return String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
window.addEventListener('hashchange',()=>{const x=location.hash.slice(1);if(NAV.some(n=>n[0]===x)){screen=x;render()}});document.addEventListener('click',e=>{const b=e.target.closest('[data-screen]');if(b)location.hash=b.dataset.screen});render();if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js?v=10.0.0').catch(()=>{}));
})();
