(()=>{'use strict';
const VERSION='11.10.0';
const DATA_KEY='mastarklass_os_10_data';
const ADMIN_KEY='mastarklass_os_10_3_1_admin';
const LIVE_FOUNDATION_KEY='mastarklass_os_11_live_foundation';
const PROVIDER_CONFIG_KEY='mastarklass_os_11_2_provider_config';
const RESOLVER_KEY='mastarklass_os_11_10_global_identity_resolver';
const SOURCE_ORDER=['openfigi','twelvedata','finnhub','yahoo','stooq','official','morningstar'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const parse=s=>{try{return JSON.parse(s)}catch{return null}};
const get=k=>parse(localStorage.getItem(k))||{};
const set=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
const norm=s=>String(s||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/\b(ab|plc|inc|ltd|corp|corporation|class|share|aktie|fond|etf|reit|adr)\b/g,' ').replace(/[^a-z0-9]+/g,' ').trim();
const sim=(a,b)=>{a=norm(a);b=norm(b);if(!a||!b)return 0;if(a===b)return 100;if(a.includes(b)||b.includes(a))return 94;const A=new Set(a.split(' ')),B=new Set(b.split(' '));const hit=[...A].filter(x=>B.has(x)).length;return Math.round(100*(2*hit)/(A.size+B.size||1));};
const state=()=>Object.assign({version:VERSION,lastRun:'',status:'ready',resolved:0,pending:0,conflicts:0,items:{},events:[],settings:{openFigiKey:'',minAutoScore:97,maxPerRun:20}},get(RESOLVER_KEY));
const save=s=>set(RESOLVER_KEY,s);
function canonicalHoldings(){
 const d=get(DATA_KEY),a=Object.assign({overrides:{},newHoldings:[]},get(ADMIN_KEY));
 const base=[...(d.holdings||[]),...(a.newHoldings||[])];
 return base.map((h,i)=>{const key=String(h.id||h.uuid||`${h.account||h.accountName||h.konto||h.platform||'Okänt'}|${h.name||h.securityName||h.title||h.instrumentName||h.symbol||h.ticker||'Innehav'}|${h.currency||h.valuta||'SEK'}|${i}`).toLowerCase();return Object.assign({},h,a.overrides[key]||{},{_key:key,_name:h.name||h.securityName||h.title||h.instrumentName||h.symbol||h.ticker||'Innehav',_account:h.account||h.accountName||h.konto||h.platform||h.broker||'Okänt',_type:h.assetType||h.type||h.category||h.tillgangsslag||h['tillgångsslag']||'Övrigt',_currency:String(h.currency||h.valuta||'SEK').toUpperCase()})})
}
function mappingStore(){const f=get(LIVE_FOUNDATION_KEY);f.mappings=f.mappings||{};return f}
function persistMapping(f){f.updatedAt=new Date().toISOString();set(LIVE_FOUNDATION_KEY,f)}
function providerConfig(){return Object.assign({twelveDataKey:'',finnhubKey:'',alphaVantageKey:''},get(PROVIDER_CONFIG_KEY))}
function inferClass(name){const n=String(name||'');const m=n.match(/(?:^|\s)(A|B|C|D|I|R|V)(?:\s|$)/i);if(/\bacc(?:umulating)?\b/i.test(n))return 'Acc';if(/\b(dist|utd|dividend)\b/i.test(n))return 'Dist';return m?m[1].toUpperCase():''}
function inferType(h){const t=norm(h._type+' '+h._name);if(/\betf\b/.test(t))return 'ETF';if(/\breit\b/.test(t))return 'REIT';if(/\badr\b/.test(t))return 'ADR';if(/fond|fund/.test(t))return 'Fond';if(/aktie|stock|equity/.test(t))return 'Aktie';return h._type||'Övrigt'}
function scoreCandidate(h,c){let score=sim(h._name,c.name||c.description||c.securityName);if(h._currency&&c.currency&&h._currency!==String(c.currency).toUpperCase())score-=10;const ht=inferType(h),ct=inferType({_type:c.type||'',_name:c.name||''});if(ht&&ct&&ht!==ct)score-=16;const hc=inferClass(h._name),cc=inferClass(c.name||'');if(hc&&cc&&hc!==cc)score-=12;if(c.isin)score+=3;if(c.exchange)score+=2;return Math.max(0,Math.min(100,score))}
async function openFigiSearch(h,key){if(!key)return[];const body=[{name:h._name}];const r=await fetch('https://api.openfigi.com/v3/mapping',{method:'POST',headers:{'Content-Type':'application/json','X-OPENFIGI-APIKEY':key},body:JSON.stringify(body)});if(!r.ok)throw new Error(`OpenFIGI HTTP ${r.status}`);const j=await r.json();return (j?.[0]?.data||[]).slice(0,8).map(x=>({source:'OpenFIGI',name:x.name||h._name,ticker:x.ticker||'',exchange:x.exchCode||'',currency:h._currency,type:x.securityType2||x.securityType||'',shareClass:inferClass(x.name),isin:'',figi:x.figi||'',providerSymbol:x.ticker||''}))}
async function twelveSearch(h,key){if(!key)return[];const u=`https://api.twelvedata.com/symbol_search?symbol=${encodeURIComponent(h._name)}&apikey=${encodeURIComponent(key)}`;const r=await fetch(u);if(!r.ok)throw new Error(`Twelve Data HTTP ${r.status}`);const j=await r.json();return (j.data||[]).slice(0,8).map(x=>({source:'Twelve Data',name:x.instrument_name||x.symbol,ticker:x.symbol||'',exchange:x.exchange||'',currency:x.currency||'',type:x.instrument_type||'',country:x.country||'',providerSymbol:x.symbol||''}))}
async function finnhubSearch(h,key){if(!key)return[];const r=await fetch(`https://finnhub.io/api/v1/search?q=${encodeURIComponent(h._name)}&token=${encodeURIComponent(key)}`);if(!r.ok)throw new Error(`Finnhub HTTP ${r.status}`);const j=await r.json();return (j.result||[]).slice(0,8).map(x=>({source:'Finnhub',name:x.description||x.displaySymbol||x.symbol,ticker:x.symbol||'',exchange:'',currency:h._currency,type:x.type||'',providerSymbol:x.symbol||''}))}
function localCandidates(h){const f=mappingStore(),m=f.mappings[h._key]||{},out=[];if(m.ticker||m.isin)out.push({source:'Lokalt register',name:m.name||h._name,ticker:m.ticker||'',isin:m.isin||'',exchange:m.exchange||'',currency:m.currency||h._currency,type:m.assetType||m.type||h._type,shareClass:inferClass(m.name||h._name),providerSymbols:m.providerSymbols||{},manual:m.source==='manual-live-mapping'});return out}
async function resolveOne(h,s){const cfg=providerConfig(),all=[...localCandidates(h)],errors=[];for(const id of SOURCE_ORDER){try{let part=[];if(id==='openfigi')part=await openFigiSearch(h,s.settings.openFigiKey);if(id==='twelvedata')part=await twelveSearch(h,cfg.twelveDataKey);if(id==='finnhub')part=await finnhubSearch(h,cfg.finnhubKey);if(['yahoo','stooq','official','morningstar'].includes(id))continue;all.push(...part)}catch(e){errors.push(String(e.message||e))}}
 const uniq=[];const seen=new Set();for(const c of all){const k=[c.source,c.ticker,c.isin,norm(c.name)].join('|');if(seen.has(k))continue;seen.add(k);c.score=scoreCandidate(h,c);uniq.push(c)}uniq.sort((a,b)=>b.score-a.score);const best=uniq[0]||null;return {key:h._key,name:h._name,account:h._account,type:inferType(h),currency:h._currency,shareClass:inferClass(h._name),best,candidates:uniq.slice(0,12),errors,updatedAt:new Date().toISOString()}}
function applyCandidate(item,c,manual=false){const f=mappingStore(),old=f.mappings[item.key]||{};if(old.source==='manual-live-mapping'&&!manual)return false;f.mappings[item.key]=Object.assign({},old,{name:item.name,account:item.account,assetType:item.type,ticker:c.ticker||old.ticker||'',isin:c.isin||old.isin||'',exchange:c.exchange||old.exchange||'',currency:c.currency||item.currency,shareClass:c.shareClass||item.shareClass||'',providerSymbols:Object.assign({},old.providerSymbols||{},c.providerSymbols||{},c.source?{[c.source]:c.providerSymbol||c.ticker||''}:{}),figi:c.figi||old.figi||'',confidence:c.score||100,verified:true,source:manual?'manual-live-mapping':'global-identity-resolver',resolverVersion:VERSION,updatedAt:new Date().toISOString()});persistMapping(f);return true}
async function runResolver(){const s=state(),hs=canonicalHoldings();s.status='running';s.lastRun=new Date().toISOString();save(s);renderPanel();let resolved=0,pending=0,conflicts=0;for(const h of hs.slice(0,s.settings.maxPerRun||20)){const item=await resolveOne(h,s);s.items[h._key]=item;if(item.best&&item.best.score>=s.settings.minAutoScore){if(applyCandidate(item,item.best))resolved++}else if(item.best)pending++;else pending++;save(s);renderPanel()}s.resolved=Object.values(s.items).filter(x=>x.best&&x.best.score>=s.settings.minAutoScore).length;s.pending=Object.values(s.items).filter(x=>!x.best||x.best.score<s.settings.minAutoScore).length;s.conflicts=conflicts;s.status='ready';s.events.unshift({at:new Date().toISOString(),text:`Resolver klar: ${resolved} automatiskt verifierade · ${pending} att granska.`});s.events=s.events.slice(0,20);save(s);renderPanel();alert(`Global Identity Resolver klar.\n${resolved} verifierade automatiskt\n${pending} att granska`)}
function reviewModal(){const s=state(),rows=Object.values(s.items).filter(x=>x.best&&x.best.score<(s.settings.minAutoScore||97)).sort((a,b)=>(b.best?.score||0)-(a.best?.score||0));const root=document.createElement('div');root.className='girModal';root.innerHTML=`<div class="girModalCard"><button class="girClose">×</button><div class="girEyebrow">GLOBAL IDENTITY RESOLVER ${VERSION}</div><h2>Granska identitetsförslag</h2><p>${rows.length} instrument behöver ditt godkännande. Portföljdata ändras aldrig.</p><div class="girReviewList">${rows.map((x,i)=>`<article><b>${esc(x.name)}</b><small>${esc(x.account)} · ${esc(x.type)}</small><div class="girCandidate"><span>${esc(x.best.source)} · ${esc(x.best.name)}</span><strong>${x.best.score}%</strong></div><div class="girMeta">${esc(x.best.ticker||'—')} · ${esc(x.best.exchange||'—')} · ${esc(x.best.currency||x.currency)} · ${esc(x.best.isin||'ISIN saknas')}</div><button data-approve="${i}">Godkänn förslag</button></article>`).join('')||'<div class="girEmpty">Inga väntande förslag.</div>'}</div></div>`;document.body.appendChild(root);root.querySelector('.girClose').onclick=()=>root.remove();root.querySelectorAll('[data-approve]').forEach(b=>b.onclick=()=>{const x=rows[Number(b.dataset.approve)];applyCandidate(x,x.best,true);const st=state();st.items[x.key].best.score=100;save(st);b.closest('article').remove();renderPanel()})}
function settingsModal(){const s=state(),k=prompt('OpenFIGI API-nyckel (lämna tomt för att behålla nuvarande):','');if(k!==null&&k.trim())s.settings.openFigiKey=k.trim();const min=prompt('Minsta säkerhet för automatisk verifiering (90–100):',String(s.settings.minAutoScore||97));if(min!==null)s.settings.minAutoScore=Math.max(90,Math.min(100,Number(min)||97));const max=prompt('Max instrument per körning:',String(s.settings.maxPerRun||20));if(max!==null)s.settings.maxPerRun=Math.max(1,Math.min(101,Number(max)||20));save(s);renderPanel()}
function panelHtml(){const s=state(),hs=canonicalHoldings(),items=Object.values(s.items),verified=items.filter(x=>x.best&&x.best.score>=s.settings.minAutoScore).length,review=items.filter(x=>x.best&&x.best.score<s.settings.minAutoScore).length,unsearched=Math.max(0,hs.length-items.length);return `<section class="girPanel" id="girPanel"><div class="girEyebrow">GLOBAL IDENTITY RESOLVER 11.10</div><div class="girTitle"><h2>Automatisk instrumentidentifiering</h2><span>${verified}/${hs.length}</span></div><p>Söker parallellt i aktiverade identitetskällor och sammanväger namn, ticker, börs, valuta, instrumenttyp och andelsklass. Endast read-only live-mapping uppdateras.</p><div class="girGrid"><div><small>Verifierade</small><b>${verified}</b></div><div><small>Att granska</small><b>${review}</b></div><div><small>Ej sökta</small><b>${unsearched}</b></div><div><small>Auto-gräns</small><b>${s.settings.minAutoScore}%</b></div></div><button id="girRun" class="girPrimary" ${s.status==='running'?'disabled':''}>${s.status==='running'?'Identifierar instrument…':'Kör Global Identity Resolver'}</button><button id="girReview">Granska förslag</button><button id="girSettings">Resolverinställningar</button><div class="girSources"><b>Källor:</b> OpenFIGI · Twelve Data · Finnhub · lokalt register<br><small>Morningstar, Yahoo Finance, Stooq och börsdatabaser är registrerade som framtida/kompatibilitetskällor men används inte automatiskt utan stabil, tillåten och CORS-kompatibel anslutning.</small></div></section>`}
function renderPanel(){const market=document.querySelector('#app');if(!market)return;let host=document.getElementById('girPanel');if(host)host.outerHTML=panelHtml();else{const anchor=[...market.querySelectorAll('section')].find(x=>/Adaptive Provider|Global Instrument|Marknad & live/i.test(x.textContent));(anchor?.parentNode||market).insertAdjacentHTML(anchor?'afterend':'afterbegin',panelHtml())}document.getElementById('girRun')?.addEventListener('click',runResolver);document.getElementById('girReview')?.addEventListener('click',reviewModal);document.getElementById('girSettings')?.addEventListener('click',settingsModal)}
const mo=new MutationObserver(()=>{if(location.hash==='#market'||/Marknad/.test(document.querySelector('nav .active')?.textContent||''))renderPanel()});
window.addEventListener('load',()=>{mo.observe(document.getElementById('app'),{childList:true,subtree:true});setTimeout(renderPanel,500)});
window.MKGlobalIdentityResolver1110={run:runResolver,state,review:reviewModal,version:VERSION};
})();
