(function(){"use strict";
const KEY="mk_masterclass_terminal_v1",seed=window.MK_MASTERCLASS_SEED||{companies:[],queue:[],etfs:[],funds:[]},copy=x=>JSON.parse(JSON.stringify(x));
let state=(()=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"null");if(x&&Array.isArray(x.companies))return x}catch(e){}return copy(seed)})();
const save=()=>localStorage.setItem(KEY,JSON.stringify(state)),esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m])),norm=s=>String(s||"").toLocaleLowerCase("sv-SE");
function initStyle(){const e=document.createElement("style");e.id="mkTerminalStyle";e.textContent=`
#mkTerminalLauncher{position:fixed;right:14px;bottom:76px;z-index:99998;border:1px solid #2b6b8d;background:linear-gradient(135deg,#0b1b2d,#0d3853);color:#eefaff;border-radius:999px;padding:11px 15px;font:800 12px system-ui;box-shadow:0 12px 36px #0008}
#mkTerminal{position:fixed;inset:0;z-index:99999;background:#04101b;color:#e8f4fb;font-family:Inter,system-ui,sans-serif;overflow:auto}#mkTerminal[hidden],.mkt-modal[hidden]{display:none}
.mkt-wrap{max-width:1500px;margin:auto;padding:14px 14px 90px}.mkt-top{position:relative;z-index:8;margin:-14px -14px 14px;padding:14px;background:#04101b;border-bottom:1px solid #18354c}
.mkt-titleRow{display:flex;gap:12px;align-items:center;justify-content:space-between}.mkt-title{font-size:21px;font-weight:950;letter-spacing:-.03em}.mkt-sub{font-size:11px;color:#8fb0c6;margin-top:3px}
.mkt-close,.mkt-btn{border:1px solid #24465f;background:#0b2133;color:#dff5ff;border-radius:10px;padding:9px 11px;font-weight:800;touch-action:manipulation}.mkt-tabs{display:flex;gap:7px;overflow-x:auto;overflow-y:hidden;margin-top:12px;padding-bottom:6px;position:relative;z-index:20;touch-action:pan-x}.mkt-tab{white-space:nowrap;position:relative;z-index:21;touch-action:manipulation;cursor:pointer;border:1px solid #1d425b;background:#071a29;color:#9db8ca;border-radius:999px;padding:8px 11px;font:800 11px system-ui}.mkt-tab.active{background:#0d4967;color:#fff;border-color:#2fb4e9}
.mkt-kpis{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin:12px 0}.mkt-kpi{background:linear-gradient(180deg,#0a2133,#071827);border:1px solid #183b54;border-radius:14px;padding:12px}.mkt-kpi span{display:block;color:#86a7bc;font-size:10px;text-transform:uppercase;letter-spacing:.08em}.mkt-kpi b{font-size:20px;display:block;margin-top:3px}
.mkt-toolbar{display:flex;gap:8px;flex-wrap:wrap;margin:12px 0}.mkt-input,.mkt-select,.mkt-textarea{background:#071725;border:1px solid #22445d;color:#e8f4fb;border-radius:10px;padding:10px;font:600 12px system-ui}.mkt-input{flex:1;min-width:180px}.mkt-select{min-width:130px}.mkt-textarea{width:100%;min-height:160px}
.mkt-tableWrap{overflow:auto;border:1px solid #17384f;border-radius:14px;background:#061521}.mkt-table{width:100%;border-collapse:collapse;min-width:1080px}.mkt-table th{position:sticky;top:0;background:#0a2437;color:#8fc6de;text-align:left;font-size:10px;letter-spacing:.06em;text-transform:uppercase;padding:10px;border-bottom:1px solid #28516a}.mkt-table td{padding:10px;border-bottom:1px solid #102e43;font-size:12px}.mkt-table tr:hover{background:#0a2234}.mkt-score{font-weight:950;font-size:14px}.mkt-pill{display:inline-flex;border-radius:999px;padding:4px 7px;font-size:10px;font-weight:900;border:1px solid #2d5972;background:#0a2639}.mkt-ref{color:#6ee7b7}.mkt-no{color:#7f9aaa}.mkt-company{font-weight:900;cursor:pointer;display:block;padding:6px 0;touch-action:manipulation}.mkt-company:hover{color:#55d0ff}.mkt-table tbody tr{cursor:pointer;touch-action:manipulation}.mkt-table tbody tr:active{background:#10314a}
.mkt-cardGrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(280px,1fr));gap:10px}.mkt-card,.mkt-section{background:linear-gradient(160deg,#0a2133,#061522);border:1px solid #1d4058;border-radius:16px;padding:14px}.mkt-card h3,.mkt-section h4{margin:0 0 6px}.mkt-card p,.mkt-section p{color:#a9c2d1;font-size:12px;line-height:1.55}.mkt-empty{border:1px dashed #29516a;border-radius:16px;padding:24px;text-align:center;color:#8aa9bc}
.mkt-modal{position:fixed;inset:0;z-index:100000;background:#000b;display:grid;place-items:center;padding:16px}.mkt-modalCard{width:min(760px,100%);max-height:90vh;overflow:auto;background:#071a28;border:1px solid #2b5b76;border-radius:20px;padding:18px}.mkt-detailTop{display:flex;justify-content:space-between;gap:10px}.mkt-detailTop h2{margin:0}.mkt-detailGrid{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:14px 0}.mkt-detailBox{background:#0a2233;border:1px solid #193c53;border-radius:12px;padding:10px}.mkt-detailBox span{display:block;color:#7d9db1;font-size:9px;text-transform:uppercase}.mkt-detailBox b{display:block;margin-top:3px}.mkt-note{background:#102818;border-color:#285e38}.mkt-danger{background:#2a1518;border-color:#6d2d37}.mkt-foot{color:#7596aa;font-size:10px;margin-top:12px}
@media(max-width:700px){.mkt-kpis{grid-template-columns:repeat(2,1fr)}.mkt-detailGrid{grid-template-columns:repeat(2,1fr)}.mkt-wrap{padding-left:9px;padding-right:9px}.mkt-top{margin-left:-9px;margin-right:-9px}}`;document.head.appendChild(e)}
function shell(){const b=document.createElement("button");b.id="mkTerminalLauncher";b.textContent="Mästarklass";b.onclick=open;document.body.appendChild(b);
const root=document.createElement("section");root.id="mkTerminal";root.hidden=true;root.innerHTML=`<div class="mkt-wrap"><div class="mkt-top"><div class="mkt-titleRow"><div><div class="mkt-title">Mästarklass Terminal</div><div class="mkt-sub">28–35 aktier · ETF:er och fonder väljs senare som kompletterande delar av utdelningsmotorn</div></div><button class="mkt-close" data-close>Stäng</button></div><div class="mkt-tabs">${["stocks|Aktier","queue|Analyskö","etfs|ETF:er","funds|Fonder","stats|Statistik","admin|Uppdatera"].map((x,i)=>{const [k,l]=x.split("|");return `<button class="mkt-tab ${i?"":"active"}" data-tab="${k}">${l}</button>`}).join("")}</div></div><div id="mktContent"></div></div>`;document.body.appendChild(root);
let lastActionAt=0;const activate=e=>{const now=Date.now();if(now-lastActionAt<220&&e.type==="click")return;lastActionAt=now;const closeBtn=e.target.closest("[data-close]");if(closeBtn){e.preventDefault();e.stopPropagation();close();return}const tab=e.target.closest("[data-tab]");if(tab&&root.contains(tab)){e.preventDefault();e.stopPropagation();root.querySelectorAll("[data-tab]").forEach(y=>y.classList.toggle("active",y===tab));render(tab.dataset.tab);return}const row=e.target.closest("tr[data-company-index]");if(row&&root.contains(row)){e.preventDefault();e.stopPropagation();detail(Number(row.dataset.companyIndex));return}};
root.addEventListener("click",activate,true);
root.addEventListener("pointerup",e=>{if(e.pointerType!=="mouse")activate(e)},true);
const m=document.createElement("div");m.className="mkt-modal";m.id="mktModal";m.hidden=true;m.innerHTML='<div class="mkt-modalCard" id="mktModalCard"></div>';document.body.appendChild(m);m.onclick=e=>{if(e.target===m)m.hidden=true}}
function open(){document.getElementById("mkTerminal").hidden=false;document.body.style.overflow="hidden";render("stocks")}function close(){document.getElementById("mkTerminal").hidden=true;document.body.style.overflow=""}
const ranked=()=>[...state.companies].sort((a,b)=>b.score-a.score||a.rank-b.rank||a.name.localeCompare(b.name,"sv"));
function kpis(){const c=state.companies;return `<div class="mkt-kpis"><div class="mkt-kpi"><span>Analyserade aktier</span><b>${c.length}</b></div><div class="mkt-kpi"><span>100 poäng</span><b>${c.filter(x=>x.score===100).length}</b></div><div class="mkt-kpi"><span>S-Core</span><b>${c.filter(x=>x.tier==="S-Core").length}</b></div><div class="mkt-kpi"><span>Slutmål aktier</span><b>28–35</b></div></div>`}
function stocks(){const cs=[...new Set(state.companies.map(x=>x.country))].sort(),ss=[...new Set(state.companies.map(x=>x.sector))].sort();return `${kpis()}<div class="mkt-toolbar"><input id="mktSearch" class="mkt-input" placeholder="Sök bolag, sektor, land, roll…"><select id="mktTier" class="mkt-select"><option value="">Alla tier</option><option>S-Core</option><option>Tier A+</option></select><select id="mktCountry" class="mkt-select"><option value="">Alla länder</option>${cs.map(x=>`<option>${esc(x)}</option>`).join("")}</select><select id="mktSector" class="mkt-select"><option value="">Alla sektorer</option>${ss.map(x=>`<option>${esc(x)}</option>`).join("")}</select><select id="mktSort" class="mkt-select"><option value="rank">Poäng/rank</option><option value="name">Namn</option><option value="country">Land</option><option value="sector">Sektor</option></select></div><div class="mkt-tableWrap"><table class="mkt-table"><thead><tr><th>#</th><th>Bolag</th><th>Land</th><th>Sektor</th><th>Poäng</th><th>Tier</th><th>Utdelning</th><th>Portföljroll</th><th>Referens</th></tr></thead><tbody id="mktRows"></tbody></table></div><div class="mkt-foot">Tryck på ett bolag för att läsa varför det kan passa Mästarklass och dess fundamentala säljsignal.</div>`}
function draw(){let q=norm(document.getElementById("mktSearch").value),t=document.getElementById("mktTier").value,c=document.getElementById("mktCountry").value,s=document.getElementById("mktSector").value,o=document.getElementById("mktSort").value,rows=ranked().filter(x=>(!q||norm([x.name,x.country,x.sector,x.role,x.dividend,x.why].join(" ")).includes(q))&&(!t||x.tier===t)&&(!c||x.country===c)&&(!s||x.sector===s));if(o==="name")rows.sort((a,b)=>a.name.localeCompare(b.name,"sv"));if(o==="country")rows.sort((a,b)=>a.country.localeCompare(b.country,"sv")||b.score-a.score);if(o==="sector")rows.sort((a,b)=>a.sector.localeCompare(b.sector,"sv")||b.score-a.score);document.getElementById("mktRows").innerHTML=rows.map((x,i)=>`<tr data-company-index="${state.companies.indexOf(x)}"><td>${i+1}</td><td><span class="mkt-company">${esc(x.name)}</span></td><td>${esc(x.flag)} ${esc(x.country)}</td><td>${esc(x.sector)}</td><td><span class="mkt-score">${x.score}</span></td><td><span class="mkt-pill">${esc(x.tier)}</span></td><td>${esc(x.dividend)}</td><td>${esc(x.role)}</td><td class="${x.reference?"mkt-ref":"mkt-no"}">${x.reference?"JA":"NEJ"}</td></tr>`).join("")}
function detail(n){const x=typeof n==="number"?state.companies[n]:state.companies.find(y=>y.name===n);if(!x)return;const m=document.getElementById("mktModal"),c=document.getElementById("mktModalCard");m.hidden=false;c.innerHTML=`<div class="mkt-detailTop"><div><small>${esc(x.flag)} ${esc(x.country)} · ${esc(x.sector)}</small><h2>${esc(x.name)}</h2></div><button class="mkt-close" data-x>Stäng</button></div><div class="mkt-detailGrid">${[["Poäng",x.score+"/100"],["Tier",x.tier],["Referens",x.reference?"Ja":"Nej"],["Utdelning",x.dividend],["Portföljroll",x.role],["Status","Kandidat – ej låst"]].map(z=>`<div class="mkt-detailBox"><span>${z[0]}</span><b>${esc(z[1])}</b></div>`).join("")}</div><div class="mkt-section mkt-note"><h4>Varför bolaget kan vara bra för Mästarklass</h4><p>${esc(x.why)}</p></div><div class="mkt-section mkt-danger"><h4>Fundamental säljsignal</h4><p>${esc(x.sell)}</p></div><div class="mkt-foot">Poäng och tier är preliminära tills hela analysuniversumet är genomgånget och slutportföljen väljs.</div>`;c.querySelector("[data-x]").onclick=()=>m.hidden=true}
function queue(){return `${kpis()}<div class="mkt-cardGrid">${state.queue.map((x,i)=>`<article class="mkt-card"><small>Analys ${state.companies.length+i+1}</small><h3>${esc(x.name)}</h3><p>${esc(x.country)} · ${esc(x.sector)}</p></article>`).join("")}</div>`}
function future(k){const a=state[k]||[],etf=k==="etfs";return `<div class="mkt-kpis"><div class="mkt-kpi"><span>${etf?"ETF-kandidater":"Fondkandidater"}</span><b>${a.length}</b></div><div class="mkt-kpi"><span>Fas</span><b>Senare</b></div><div class="mkt-kpi"><span>Syfte</span><b>Utdelningsmotor</b></div><div class="mkt-kpi"><span>Aktiemål</span><b>28–35</b></div></div><div class="mkt-section"><h4>${etf?"ETF:er":"Fonder"} kompletterar aktierna</h4><p>${etf?"ETF:erna ska ge riskspridning, geografisk balans och utdelningsflöden utan att ersätta kvalitetsurvalet av aktier.":"Fonderna väljs efter aktieurvalet som breda byggstenar där fondformatet är effektivare."}</p></div>${a.length?`<div class="mkt-cardGrid">${a.map(x=>`<article class="mkt-card"><h3>${esc(x.name)}</h3></article>`).join("")}</div>`:'<div class="mkt-empty">Inga kandidater är låsta ännu.</div>'}`}
function stats(){const by=k=>Object.entries(state.companies.reduce((a,x)=>(a[x[k]]=(a[x[k]]||0)+1,a),{})).sort((a,b)=>b[1]-a[1]),box=(t,d)=>`<article class="mkt-card"><h3>${t}</h3>${d.map(x=>`<p><b>${esc(x[0])}</b> · ${x[1]}</p>`).join("")}</article>`;return `${kpis()}<div class="mkt-cardGrid">${box("Länder",by("country"))}${box("Sektorer",by("sector"))}${box("Tier",by("tier"))}${box("Utdelningsprofiler",by("dividend"))}</div>`}
function admin(){return `<div class="mkt-section"><h4>Uppdatera utan nya appfiler</h4><p>Klistra in JSON från nästa analys. Bolaget läggs till eller uppdateras lokalt. Exportera backup när du vill.</p></div><div class="mkt-toolbar"><button class="mkt-btn" id="mktTemplate">Mall</button><button class="mkt-btn" id="mktImport">Importera</button><button class="mkt-btn" id="mktExport">Exportera backup</button><button class="mkt-btn" id="mktReset">Återställ</button></div><textarea id="mktJson" class="mkt-textarea"></textarea><div id="mktMsg" class="mkt-foot"></div>`}
function bindAdmin(){const ta=document.getElementById("mktJson"),msg=document.getElementById("mktMsg");document.getElementById("mktTemplate").onclick=()=>ta.value=JSON.stringify({name:"Nytt bolag",country:"Land",flag:"🏳️",sector:"Sektor",score:98,tier:"S-Core",dividend:"Utdelningstillväxt",role:"Portföljroll",reference:false,why:"Varför bolaget kan passa.",sell:"Fundamental säljsignal."},null,2);document.getElementById("mktImport").onclick=()=>{try{let a=JSON.parse(ta.value);if(!Array.isArray(a))a=[a];a.forEach(x=>{if(!x.name)throw Error("Bolagsnamn saknas");let i=state.companies.findIndex(y=>y.name===x.name);i<0?state.companies.push({...x,rank:state.companies.length+1}):state.companies[i]={...state.companies[i],...x};state.queue=state.queue.filter(y=>y.name!==x.name)});save();msg.textContent=`Klart: ${a.length} post(er) importerades.`}catch(e){msg.textContent="Fel: "+e.message}};document.getElementById("mktExport").onclick=()=>{const a=document.createElement("a"),u=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:"application/json"}));a.href=u;a.download="mastarklass_masterlista_backup.json";a.click();URL.revokeObjectURL(u)};document.getElementById("mktReset").onclick=()=>{if(confirm("Återställa grunddata?")){state=copy(seed);save();render("admin")}}}
function render(t){const c=document.getElementById("mktContent");c.innerHTML=t==="stocks"?stocks():t==="queue"?queue():t==="etfs"?future("etfs"):t==="funds"?future("funds"):t==="stats"?stats():admin();if(t==="stocks"){["mktSearch","mktTier","mktCountry","mktSector","mktSort"].forEach(id=>document.getElementById(id).addEventListener(id==="mktSearch"?"input":"change",draw));draw()}if(t==="admin")bindAdmin()}
function init(){if(document.getElementById("mkTerminal"))return;initStyle();shell()}document.readyState==="loading"?document.addEventListener("DOMContentLoaded",init):init();
})();